import fs from'node:fs';
import vm from'node:vm';
import assert from'node:assert/strict';
const context=vm.createContext({Date,JSON,Utilities:{formatDate:d=>d.toISOString().slice(0,10)},READY:{TZ:'Asia/Seoul'}});
for(const file of ['ReadmeService.gs','GithubService.gs','ReadinessService.gs'])vm.runInContext(fs.readFileSync('apps-script/'+file,'utf8'),context,{filename:file});
const call=(expression)=>vm.runInContext(expression,context);
const commits=(days)=>days.map(day=>({commit:{author:{date:new Date(Date.now()-day*86400000).toISOString()}}}));
context.sample=commits([1,1,1,3,3,5]);assert.equal(call('activityDates(sample,7).length'),3);
context.sample=commits(Array(20).fill(1));assert.equal(call('activityDates(sample,7).length'),1);assert.equal(call('githubActivityStatus(1,1)'),'활동 부족');
assert.equal(call("analyzeReadme('').readme_status"),'README 미작성');
context.sample='## 프로젝트 소개\n학생 취업준비 프로젝트의 핵심 기능을 설명합니다.\n## 개발 목적\n학생이 자신의 활동을 점검하도록 만들었습니다.\n## 주요 기능\n자동 점검과 현황 조회 기능을 제공합니다.\n## 기술 스택\nJavaScript와 Google Apps Script를 사용했습니다.\n## 실행 방법\n환경 설정 후 브라우저에서 실행합니다.';
assert.equal(call('analyzeReadme(sample).readme_status'),'README 보완 필요');assert.equal(call('analyzeReadme(sample).role'),false);assert.equal(call('analyzeReadme(sample).troubleshooting'),false);
context.sample+='\n## 본인 역할\n개발했습니다.\n## 트러블슈팅\n문제를 해결했습니다.';assert.equal(call('analyzeReadme(sample).role'),false);assert.equal(call('analyzeReadme(sample).troubleshooting'),false);
context.student={grade:'1',notion_url:'https://notion.so/example'};context.checks={github:{check_status:'SUCCESS',active_days_7d:3,inactive_days:1},repository:{check_status:'SUCCESS',description_exists:true,topics_count:1,gitignore_exists:true,license_exists:false},readme:{readme_status:'README 양호',readme_exists:true,role:true,troubleshooting:true},notion:{check_status:'SUCCESS',activity_status:'최근 업데이트'},blog:{},repositoryCount:1};
assert.equal(call('evaluateStudentReadiness(student,checks).status'),'준비 우수');assert.equal(call('evaluateStudentReadiness(student,checks).issues.find(x=>x.code==="license").required'),false);
context.student.grade='2';assert.notEqual(call('evaluateStudentReadiness(student,checks).status'),'준비 우수');context.student.resume_status='최종 완성';context.student.cover_letter_status='기본본 완성';assert.equal(call('evaluateStudentReadiness(student,checks).status'),'준비 우수');
context.checks.repository.description_exists=false;context.checks.repository.topics_count=0;context.checks.repository.gitignore_exists=false;assert.equal(call('evaluateStudentReadiness(student,checks).issues.some(x=>x.code==="description")'),true);assert.equal(call('evaluateStudentReadiness(student,checks).issues.some(x=>x.code==="topic")'),true);assert.equal(call('evaluateStudentReadiness(student,checks).issues.some(x=>x.code==="gitignore")'),true);
context.checks.repository.visibility='Private';context.checks.repository.branch_count=1;assert.equal(call('evaluateStudentReadiness(student,checks).issues.some(x=>x.code==="visibility"||x.code==="branch")'),false);
context.student.grade='1';context.student.resume_status='미작성';context.student.cover_letter_status='미작성';context.checks.repository.description_exists=true;context.checks.repository.topics_count=1;context.checks.repository.gitignore_exists=true;assert.equal(call('evaluateStudentReadiness(student,checks).status'),'준비 우수');
context.checks.github.active_days_7d=1;assert.notEqual(call('evaluateStudentReadiness(student,checks).status'),'준비 우수');
const sampleRows={STUDENTS:[{student_id:'1',name:'테스트 학생',grade:'1',career_target:'개발자',notion_url:'https://notion.so/x',active:true}],REPOSITORIES:[{repo_id:'r1',student_id:'1',active:true,is_primary:true}],CERTIFICATES:[],GITHUB_CHECK:[{student_id:'1',checked_at:'2026-10-02',active_days_7d:3,check_status:'SUCCESS',inactive_days:1}],REPOSITORY_CHECK:[{repo_id:'r1',checked_at:'2026-10-02',check_status:'SUCCESS',description_exists:true,topics_count:1,gitignore_exists:true}],README_CHECK:[{repo_id:'r1',checked_at:'2026-10-02',readme_status:'README 양호',readme_exists:true,role:true,troubleshooting:true}],NOTION_CHECK:[{student_id:'1',checked_at:'2026-10-02',check_status:'SUCCESS',activity_status:'최근 업데이트'}],PORTFOLIO_CHECK:[],BLOG_CHECK:[],CHECK_LOG:[]};
context.rows=name=>sampleRows[name]||[];context.active=name=>(sampleRows[name]||[]).filter(x=>x.active!==false);context.safeRow=x=>({...x});context.now=()=>new Date().toISOString();context.today=()=>new Date().toISOString().slice(0,10);
vm.runInContext(fs.readFileSync('apps-script/DashboardService.gs','utf8'),context,{filename:'DashboardService.gs'});
assert.equal(call('getPublicSummary().student_activity[0].preparation_status'),call('getAdminDashboard().students[0].preparation_status'));
assert.equal(call('getPublicSummary().student_activity[0].student_id'),undefined);
console.log('Readiness checks passed');
