function latestMap(name,key){const out={};rows(name).sort((a,b)=>String(a.checked_at||'').localeCompare(String(b.checked_at||''))).forEach(x=>out[String(x[key])]=x);return out}
function getMyDashboard(session){const profile=getMyProfile(session),c=readinessContext(),item=evaluatedStudent(profile.student,c);return{student:profile.student,github:safeRow(item.github),blog:safeRow(item.blog),notion:safeRow(item.notion),portfolio_check:safeRow(item.portfolioCheck||{}),repository:safeRow(item.repository),readme:safeRow(item.readme),evaluation:item.evaluation,repositories:item.repositories.map(r=>Object.assign(safeRow(r),safeRow(c.repository[String(r.repo_id)]||{}),{readme_check:safeRow(c.readme[String(r.repo_id)]||{})})),suggestions:item.evaluation.priorityIssues.map(x=>x.label),readiness_guide:readinessGuide()}}
function publicPortfolioLink(item){
  const check=item.portfolioCheck||{};
  try{
    const entries=JSON.parse(check.url_results||'[]');
    if(Array.isArray(entries)){const verified=entries.find(x=>x.available&&/^https?:\/\//i.test(String(x.url||'')));if(verified)return String(verified.url)}
  }catch(e){}
  return ''
}
function publicStudent(item){const s=item.student,e=item.evaluation,g=item.github,n=item.notion;return{name:String(s.name||''),grade:String(s.grade||''),career_target:String(s.career_target||''),preparation_status:e.status,active_days_7d:Number(g.active_days_7d||0),active_days_14d:Number(g.active_days_14d||0),commits_7d:Number(g.commits_7d||0),last_activity_at:g.last_activity_at||'',github_active_7d:['SUCCESS','PARTIAL'].includes(String(g.check_status||''))&&Number(g.active_days_7d||0)>=3,github_activity_status:g.activity_status||'미점검',repository_count:item.repositories.length,readme_status:item.readme.readme_status||'미점검',portfolio_registered:e.portfolio.registered,portfolio_status:e.portfolio.status,notion_registered:Boolean(s.notion_url),notion_last_edited_at:n.last_edited_at||'',notion_activity_status:n.activity_status||(!s.notion_url?'미등록':'미점검'),notion_check_status:n.check_status||'미점검',resume_status:String(s.grade)==='2'?(s.resume_status||'미작성'):'',cover_letter_status:String(s.grade)==='2'?(s.cover_letter_status||'미작성'):'',certificate_count:item.certificateCount,job_ready:String(s.grade)==='2'&&e.status==='준비 우수',issues:e.issues.map(x=>x.label),priority_issues:e.priorityIssues.map(x=>x.label),priority_issue_details:e.priorityIssues.map(x=>({code:x.code,label:x.label,why:x.why,how:x.how,evidence:x.evidence,level:x.level,area:x.area})),github_fresh:e.github_fresh,github_checked_at:e.github_checked_at,github_check_status:g.check_status||'미점검',github_url:String(s.github_url||''),primary_repository_url:item.repository.visibility==='Public'?String(item.repositories[0]?.repo_url||''):'',public_portfolio_url:publicPortfolioLink(item)}}
function publicStudents(){const c=readinessContext();return active('STUDENTS').map(s=>publicStudent(evaluatedStudent(s,c)))}
function getClassDashboard(){const ss=publicStudents();return{summary:{'전체 학생':ss.length,'최근 7일 GitHub 활동':ss.filter(x=>x.github_active_7d).length,'Notion 등록':ss.filter(x=>x.notion_registered).length,'준비 우수':ss.filter(x=>x.preparation_status==='준비 우수').length},students:ss}}
function recentPublicUpdates(){
  const students=Object.fromEntries(active('STUDENTS').map(s=>[String(s.student_id),String(s.name||'')]));
  const types={'등록':{'student':'READY 신규 등록'},'Repository':{'추가':'프로젝트 Repository 등록'},'자격증':{'추가':'자격증 정보 등록','상태':'자격증 상태 수정'},'프로필':{
    'github_url':'GitHub 정보 수정','github_pages_url':'GitHub Pages 정보 수정',
    'github_pages_repo':'기술블로그 저장소 수정','notion_url':'Notion 정보 수정',
    'portfolio_url':'포트폴리오 정보 수정','blog_url':'기술블로그 정보 수정',
    'resume_status':'이력서 준비상태 수정','cover_letter_status':'자기소개서 준비상태 수정'
  }};
  const cutoff=Date.now()-7*86400000;
  return rows('CHANGE_HISTORY').filter(x=>students[String(x.student_id)]&&types[x.category]&&types[x.category][x.field_name]&&new Date(x.changed_at).getTime()>=cutoff)
    .sort((a,b)=>String(b.changed_at).localeCompare(String(a.changed_at)))
    .slice(0,8).map(x=>({name:students[String(x.student_id)],label:types[x.category][x.field_name],changed_at:x.changed_at}));
}
function getPublicSummary(){const ss=publicStudents().sort((a,b)=>a.name.localeCompare(b.name,'ko'));return{total_students:ss.length,grade1:ss.filter(x=>x.grade==='1').length,grade2:ss.filter(x=>x.grade==='2').length,github_active_7d:ss.filter(x=>x.github_active_7d).length,portfolio_registered:ss.filter(x=>x.portfolio_registered).length,job_ready:ss.filter(x=>x.job_ready).length,student_activity:ss,recent_updates:recentPublicUpdates(),readiness_guide:readinessGuide(),updated_at:now()}}
function getAdminDashboard(){const c=readinessContext(),items=active('STUDENTS').map(s=>{const item=evaluatedStudent(s,c),p=publicStudent(item);return Object.assign({},p,{student_id:s.student_id,github:{activity_status:item.github.activity_status||'미점검',check_status:item.github.check_status||'미점검',active_days_7d:p.active_days_7d,active_days_14d:p.active_days_14d,commits_7d:p.commits_7d,commits_30d:Number(item.github.commits_30d||0),inactive_days:item.github.inactive_days,last_activity_at:item.github.last_activity_at||''},repository:{description_exists:item.repository.description_exists,topics_count:item.repository.topics_count,gitignore_exists:item.repository.gitignore_exists},portfolio:{notion:Boolean(s.notion_url),personal:Boolean(s.portfolio_url),pages:Boolean(s.github_pages_url),blog:Boolean(s.blog_url)},certificate_count:item.certificateCount,reasons:item.evaluation.issues.map(x=>x.label),priority_issues:item.evaluation.priorityIssues.map(x=>x.label)})}),logs=rows('CHECK_LOG').filter(x=>String(x.started_at).startsWith(today()));return{summary:{total:items.length,grade1:items.filter(x=>x.grade==='1').length,grade2:items.filter(x=>x.grade==='2').length,gradeUnset:items.filter(x=>!x.grade).length,excellent:items.filter(x=>x.preparation_status==='준비 우수').length,good:items.filter(x=>x.preparation_status==='준비 양호').length,progress:items.filter(x=>x.preparation_status==='준비 중').length,attention:items.filter(x=>x.preparation_status==='관심 필요').length,githubActive:items.filter(x=>x.github_active_7d).length,checkToday:logs.reduce((a,x)=>a+Number(x.success_count||0),0)+' / '+logs.reduce((a,x)=>a+Number(x.failed_count||0),0)},students:items,readiness_guide:readinessGuide()}}
function getAdminStudentDetail(_,sid){const s=active('STUDENTS').find(x=>String(x.student_id)===String(sid));if(!s)throw publicError('NOT_FOUND','학생 정보를 찾을 수 없습니다.');const c=readinessContext(),item=evaluatedStudent(s,c),memo=rows('PROFESSOR_MEMO').find(x=>String(x.student_id)===String(sid));return{student:safeRow(s),evaluation:item.evaluation,repositories:item.repositories.map(r=>Object.assign(safeRow(r),safeRow(c.repository[String(r.repo_id)]||{}),{readme_check:safeRow(c.readme[String(r.repo_id)]||{})})),certificates:active('CERTIFICATES').filter(x=>String(x.student_id)===String(sid)).map(safeRow),history:getChangeHistory(sid),readiness_guide:readinessGuide(),checks:{github:safeRow(item.github),blog:safeRow(item.blog),notion:safeRow(item.notion),portfolio:safeRow(item.portfolioCheck||{})},memo:memo?safeRow(memo):null}}
function saveProfessorMemo(_,req){const existing=rows('PROFESSOR_MEMO').find(x=>String(x.student_id)===String(req.student_id)),t=now(),o={memo_id:existing?existing.memo_id:id('memo'),student_id:req.student_id,memo_text:String(req.memo_text||''),created_at:existing?existing.created_at:t,updated_at:t};upsert('PROFESSOR_MEMO','student_id',o);history(req.student_id,'교수 메모','memo','', '[비공개 메모 수정]','ADMIN');return{saved:true}}
