function latestMap(name,key){const out={};rows(name).sort((a,b)=>String(a.checked_at||'').localeCompare(String(b.checked_at||''))).forEach(x=>out[String(x[key])]=x);return out}
function getMyDashboard(s){const p=getMyProfile(s),gm=latestMap('GITHUB_CHECK','student_id'),bm=latestMap('BLOG_CHECK','student_id'),g=gm[String(s.student_id)]||{},suggest=[];if(String(p.student.grade)==='2'&&(p.student.cover_letter_status==='미작성'||p.student.cover_letter_status==='작성중'))suggest.push('자기소개서 준비 상태를 확인해 보세요.');if(Number(g.active_repository_count||0)>Number(g.readme_count||0))suggest.push('대표 Repository의 README를 보완해 보세요.');if(Number(g.inactive_days||0)>=14)suggest.push('최근 GitHub 활동이 뜸합니다. 진행 중인 작업을 정리해 보세요.');if(!p.student.notion_url)suggest.push('Notion 포트폴리오가 아직 등록되지 않았습니다.');return{student:p.student,github:safeRow(g),blog:safeRow(bm[String(s.student_id)]||{}),suggestions:suggest}}
function publicStudents(){const students=active('STUDENTS'),gm=latestMap('GITHUB_CHECK','student_id'),bm=latestMap('BLOG_CHECK','student_id'),repos=active('REPOSITORIES'),certs=active('CERTIFICATES');return students.map(s=>({student_id:s.student_id,name:s.name,grade:String(s.grade||''),career_target:s.career_target,last_activity_at:(gm[String(s.student_id)]||{}).last_activity_at||'',github_active_7d:Number((gm[String(s.student_id)]||{}).commits_7d||0)>0,repository_count:repos.filter(r=>String(r.student_id)===String(s.student_id)).length,blog_last_activity:(bm[String(s.student_id)]||{}).last_repo_commit_at||'',notion_registered:Boolean(s.notion_url),resume_status:s.resume_status,cover_letter_status:s.cover_letter_status,certificate_count:certs.filter(c=>String(c.student_id)===String(s.student_id)&&c.status==='취득').length}))}
function getClassDashboard(){const ss=publicStudents();return{summary:{'전체 학생':ss.length,'최근 7일 GitHub 활동':ss.filter(x=>x.github_active_7d).length,'Notion 등록':ss.filter(x=>x.notion_registered).length,'이력서 최종완성':ss.filter(x=>x.resume_status==='최종 완성').length,'자기소개서 완성':ss.filter(x=>['기본본 완성','기업 지원 가능'].includes(x.cover_letter_status)).length,'자격증 보유':ss.filter(x=>x.certificate_count>0).length},students:ss}}
function getPublicSummary(){
  const summary=getClassDashboard().summary,gm=latestMap('GITHUB_CHECK','student_id'),nm=latestMap('NOTION_CHECK','student_id'),students=active('STUDENTS'),repos=active('REPOSITORIES');
  const activity=students.map(x=>{const g=gm[String(x.student_id)]||{},n=nm[String(x.student_id)]||{},repositoryCount=repos.filter(r=>String(r.student_id)===String(x.student_id)).length,portfolioReady=Boolean(x.notion_url||x.portfolio_url||x.github_pages_url||x.blog_url),isSecond=String(x.grade)==='2',resumeReady=isSecond&&x.resume_status==='최종 완성',coverReady=isSecond&&['기본본 완성','기업 지원 가능'].includes(x.cover_letter_status),jobReady=isSecond&&resumeReady&&coverReady,signals=[Number(g.commits_7d||0)>0,repositoryCount>0,portfolioReady].filter(Boolean).length+(isSecond&&jobReady?1:0),target=isSecond?4:3;return{name:String(x.name||''),grade:String(x.grade||''),career_target:String(x.career_target||''),github_active_7d:Number(g.commits_7d||0)>0,commits_7d:Number(g.commits_7d||0),repository_count:repositoryCount,portfolio_registered:portfolioReady,notion_registered:Boolean(x.notion_url),notion_last_edited_at:n.last_edited_at||'',notion_activity_status:n.activity_status||(!x.notion_url?'미등록':'미점검'),notion_check_status:n.check_status||'미점검',resume_status:isSecond?(x.resume_status||'미작성'):'',cover_letter_status:isSecond?(x.cover_letter_status||'미작성'):'',certificate_count:active('CERTIFICATES').filter(c=>String(c.student_id)===String(x.student_id)&&c.status==='취득').length,job_ready:jobReady,preparation_status:signals>=target?'준비 우수':signals>=1?'진행 중':'관심 필요'}}).sort((a,b)=>b.commits_7d-a.commits_7d||b.repository_count-a.repository_count||a.name.localeCompare(b.name,'ko'));
  return{total_students:summary['전체 학생'],grade1:students.filter(x=>String(x.grade)==='1').length,grade2:students.filter(x=>String(x.grade)==='2').length,github_active_7d:summary['최근 7일 GitHub 활동'],portfolio_registered:summary['Notion 등록'],job_ready:activity.filter(x=>x.job_ready).length,student_activity:activity.slice(0,40),updated_at:now()};
}

function readinessForAdmin(student,github,repositoryCount,certificateCount){
  const githubReady=Number(github.commits_30d||0)>0&&github.check_status!=='FAILED';
  const portfolioReady=Boolean(student.notion_url||student.portfolio_url||student.github_pages_url||student.blog_url);
  const isSecond=String(student.grade)==='2',resumeReady=isSecond&&student.resume_status==='최종 완성',coverReady=isSecond&&['기본본 완성','기업 지원 가능'].includes(student.cover_letter_status);
  const completed=[githubReady,repositoryCount>0,portfolioReady].filter(Boolean).length+(isSecond&&resumeReady?1:0)+(isSecond&&coverReady?1:0),target=isSecond?4:3;
  return completed>=target?'준비 우수':completed>=1?'진행 중':'관심 필요';
}

function getAdminDashboard(){
  const students=active('STUDENTS'),gm=latestMap('GITHUB_CHECK','student_id'),bm=latestMap('BLOG_CHECK','student_id'),repos=active('REPOSITORIES'),certs=active('CERTIFICATES');
  const items=students.map(s=>{
    const g=gm[String(s.student_id)]||{},b=bm[String(s.student_id)]||{},studentRepos=repos.filter(r=>String(r.student_id)===String(s.student_id)),studentCerts=certs.filter(c=>String(c.student_id)===String(s.student_id)&&c.status==='취득'),reasons=[];
    if(Number(g.inactive_days)>=14)reasons.push('14일 이상 미활동');
    if(!studentRepos.length)reasons.push('Repository 미등록');
    if(!s.notion_url&&!s.portfolio_url&&!s.github_pages_url&&!s.blog_url)reasons.push('포트폴리오 미등록');
    if(String(s.grade)==='2'&&s.resume_status!=='최종 완성')reasons.push('이력서 미완성');
    if(String(s.grade)==='2'&&!['기본본 완성','기업 지원 가능'].includes(s.cover_letter_status))reasons.push('자기소개서 미완성');
    if(g.check_status==='FAILED')reasons.push('자동점검 실패');
    return{student_id:s.student_id,name:s.name,grade:String(s.grade||''),career_target:s.career_target,preparation_status:readinessForAdmin(s,g,studentRepos.length,studentCerts.length),github:{activity_status:g.activity_status||'미점검',check_status:g.check_status||'미점검',commits_7d:Number(g.commits_7d||0),commits_30d:Number(g.commits_30d||0),inactive_days:g.inactive_days===''?'':Number(g.inactive_days||0),last_activity_at:g.last_activity_at||''},repository_count:studentRepos.length,readme_count:Number(g.readme_count||0),portfolio:{notion:Boolean(s.notion_url),personal:Boolean(s.portfolio_url),pages:Boolean(s.github_pages_url),blog:Boolean(s.blog_url),blog_available:String(b.site_available).toLowerCase()==='true'},resume_status:s.resume_status||'미작성',cover_letter_status:s.cover_letter_status||'미작성',certificate_count:studentCerts.length,reasons:reasons};
  });
  const logs=rows('CHECK_LOG').filter(x=>String(x.started_at).startsWith(today()));
  return{summary:{total:items.length,grade1:items.filter(x=>x.grade==='1').length,grade2:items.filter(x=>x.grade==='2').length,gradeUnset:items.filter(x=>!x.grade).length,excellent:items.filter(x=>x.preparation_status==='준비 우수').length,progress:items.filter(x=>x.preparation_status==='진행 중').length,attention:items.filter(x=>x.preparation_status==='관심 필요').length,githubActive:items.filter(x=>x.github.commits_7d>0).length,checkToday:logs.reduce((a,x)=>a+Number(x.success_count||0),0)+' / '+logs.reduce((a,x)=>a+Number(x.failed_count||0),0)},students:items};
}

function getAdminStudentDetail(_,sid){const s=active('STUDENTS').find(x=>String(x.student_id)===String(sid));if(!s)throw publicError('NOT_FOUND','학생 정보를 찾을 수 없습니다.');const repos=active('REPOSITORIES').filter(x=>String(x.student_id)===String(sid)),rm=latestMap('REPOSITORY_CHECK','repo_id'),memo=rows('PROFESSOR_MEMO').find(x=>String(x.student_id)===String(sid));return{student:safeRow(s),repositories:repos.map(r=>Object.assign(safeRow(r),safeRow(rm[r.repo_id]||{}))),certificates:active('CERTIFICATES').filter(x=>String(x.student_id)===String(sid)).map(safeRow),history:getChangeHistory(sid),checks:{github:(latestMap('GITHUB_CHECK','student_id')[String(sid)]||{}),blog:(latestMap('BLOG_CHECK','student_id')[String(sid)]||{})},memo:memo?safeRow(memo):null}}
function saveProfessorMemo(_,req){const existing=rows('PROFESSOR_MEMO').find(x=>String(x.student_id)===String(req.student_id)),t=now(),o={memo_id:existing?existing.memo_id:id('memo'),student_id:req.student_id,memo_text:String(req.memo_text||''),created_at:existing?existing.created_at:t,updated_at:t};upsert('PROFESSOR_MEMO','student_id',o);history(req.student_id,'교수 메모','memo','', '[비공개 메모 수정]','ADMIN');return{saved:true}}
