function gh(path,optional){const token=props().getProperty('GITHUB_TOKEN');if(!token)throw publicError('CONFIG_ERROR','GitHub 연동 설정이 필요합니다.');const r=UrlFetchApp.fetch('https://api.github.com'+path,{headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'READY-portfolio-monitor'},muteHttpExceptions:true});const code=r.getResponseCode();if(code===404&&optional)return null;if(code<200||code>=300){const e=publicError('GITHUB_ERROR',code===404?'등록한 GitHub 정보를 확인할 수 없습니다.':'GitHub 정보를 확인하지 못했습니다.');e.technical='GitHub HTTP '+code+' '+r.getContentText().slice(0,300);throw e}return JSON.parse(r.getContentText())}
function isoDaysAgo(n){return new Date(Date.now()-n*86400000).toISOString()}
function activityDates(commits,days){const earliest=Date.now()-days*86400000;return [...new Set(commits.map(c=>c.commit&&c.commit.author&&c.commit.author.date||'').filter(d=>d&&new Date(d).getTime()>=earliest).map(d=>Utilities.formatDate(new Date(d),READY.TZ,'yyyy-MM-dd')))]}
function githubActivityStatus(days,inactive){if(days>=3)return '정상';if(days===2)return '보완 필요';if(days===1)return '활동 부족';return inactive>=14?'장기 미활동':'미활동'}
function githubRecencyStatus(inactive){if(inactive==='')return '미점검';const days=Number(inactive);return days<=3?'정상':days<=6?'활동 필요':days<=13?'활동 부족':'장기 미활동'}
function pushStatus(date){if(!date)return '미점검';const days=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/86400000));return days<=7?'정상':days<=14?'관심':days<=29?'업데이트 필요':'장기 미업데이트'}
function repoCommits(base,username){const since=encodeURIComponent(isoDaysAgo(30)),author=username?'&author='+encodeURIComponent(username):'',all=[];for(let page=1;page<=3;page++){const batch=gh(base+'/commits?since='+since+author+'&per_page=100&page='+page,true)||[];all.push(...batch);if(batch.length<100)break}return all}
function checkRepository(student,repo,full){const base='/repos/'+encodeURIComponent(repo.repo_owner)+'/'+encodeURIComponent(repo.repo_name),meta=gh(base),commits=repoCommits(base,student.github_username),dates=commits.map(c=>c.commit&&c.commit.author&&c.commit.author.date).filter(Boolean).sort().reverse(),last=dates[0]||'',seven=commits.filter(c=>new Date(c.commit.author.date).getTime()>=Date.now()-7*86400000),result={repo_id:repo.repo_id,student_id:student.student_id,checked_at:now(),last_commit_at:last,last_push_at:meta.pushed_at||'',commits_7d:seven.length,commits_30d:commits.length,student_commits_7d:seven.length,student_commits_30d:commits.length,active_days_7d:activityDates(commits,7).length,active_days_14d:activityDates(commits,14).length,primary_language:meta.language||'',github_updated_at:meta.updated_at||'',visibility:meta.private?'Private':'Public',push_status:pushStatus(meta.pushed_at),check_status:'SUCCESS',error_message:''};
  result.activity_dates_14d=JSON.stringify(activityDates(commits,14));
  if(full){const readme=gh(base+'/readme',true),ignore=gh(base+'/contents/.gitignore',true),license=meta.license||gh(base+'/license',true),branches=gh(base+'/branches?per_page=100',true)||[];let markdown='';if(readme&&readme.content){try{markdown=Utilities.newBlob(Utilities.base64Decode(readme.content.replace(/\s/g,''))).getDataAsString()}catch(e){markdown=''}}const analysis=analyzeReadme(markdown);result.readme_exists=Boolean(readme);result.gitignore_exists=Boolean(ignore);result.license_exists=Boolean(license);result.description_exists=Boolean(String(meta.description||'').trim());result.topics=JSON.stringify(meta.topics||[]);result.topics_count=(meta.topics||[]).length;result.branch_count=branches.length;upsert('README_CHECK','repo_id',Object.assign({repo_id:repo.repo_id,student_id:student.student_id,checked_at:result.checked_at,readme_exists:Boolean(readme),check_status:'SUCCESS',error_message:''},analysis))}
  upsert('REPOSITORY_CHECK','repo_id',result);return result}
function detectBlog(student){if(!student.github_pages_url&&!student.github_pages_repo)return{student_id:student.student_id,checked_at:now(),site_available:false,platform_type:'미등록',check_status:'SUCCESS',error_message:''};let available=false;try{if(student.github_pages_url){const r=UrlFetchApp.fetch(student.github_pages_url,{muteHttpExceptions:true,followRedirects:true});available=r.getResponseCode()>=200&&r.getResponseCode()<400}}catch(e){}let last='',platform='URL';const p=githubParts(student.github_pages_repo);if(p&&p.repo){const meta=gh('/repos/'+p.owner+'/'+p.repo,true);if(meta){last=meta.pushed_at||'';for(const candidate of [{path:'_posts',type:'Jekyll'},{path:'content',type:'Hugo'},{path:'posts',type:'Posts'},{path:'blog',type:'Blog'}]){if(gh('/repos/'+p.owner+'/'+p.repo+'/contents/'+candidate.path,true)){platform=candidate.type;break}}}}return{student_id:student.student_id,checked_at:now(),site_available:available,last_repo_commit_at:last,last_post_date:'',posts_30d:'',platform_type:platform,check_status:'SUCCESS',error_message:''}}
function checkStudent(student){
  const repos=active('REPOSITORIES').filter(r=>String(r.student_id)===String(student.student_id)).sort((a,b)=>Number(String(b.is_primary).toLowerCase()==='true')-Number(String(a.is_primary).toLowerCase()==='true')||Number(a.display_order||99)-Number(b.display_order||99)),results=[],errors=[];
  repos.forEach(r=>{try{results.push(checkRepository(student,r,true))}catch(e){errors.push(r.repo_name+': '+(e.technical||e.message));upsert('REPOSITORY_CHECK','repo_id',{repo_id:r.repo_id,student_id:student.student_id,checked_at:now(),check_status:'FAILED',error_message:e.technical||e.message})}});
  const last=results.map(x=>x.last_commit_at).filter(Boolean).sort().reverse()[0]||'',inactive=last?Math.max(0,Math.floor((Date.now()-new Date(last).getTime())/86400000)):'',allDates=[...new Set(results.flatMap(x=>JSON.parse(x.activity_dates_14d||'[]')))],cutoff=Utilities.formatDate(new Date(Date.now()-7*86400000),READY.TZ,'yyyy-MM-dd'),days7=allDates.filter(x=>x>=cutoff).length,days14=allDates.length;
  const g={student_id:student.student_id,checked_at:now(),last_activity_at:last,commits_7d:results.reduce((n,x)=>n+Number(x.student_commits_7d||0),0),commits_30d:results.reduce((n,x)=>n+Number(x.student_commits_30d||0),0),active_days_7d:days7,active_days_14d:days14,active_repository_count:repos.length,readme_count:results.filter(x=>x.readme_exists).length,inactive_days:inactive,activity_status:!repos.length?'미등록':githubActivityStatus(days7,inactive),recency_status:githubRecencyStatus(inactive),check_status:errors.length?'FAILED':'SUCCESS',error_message:errors.join(' | ')};
  upsert('GITHUB_CHECK','student_id',g);
  try{upsert('BLOG_CHECK','student_id',detectBlog(student))}catch(e){upsert('BLOG_CHECK','student_id',{student_id:student.student_id,checked_at:now(),check_status:'FAILED',error_message:e.technical||e.message})}
  if(errors.length)throw publicError('CHECK_FAILED','일부 GitHub 정보를 확인하지 못했습니다.');return g
}
