function evaluateStudentReadiness(student,checks){const g=checks.github||{},repo=checks.repository||{},readme=checks.readme||{},notion=checks.notion||{},blog=checks.blog||{},count=Number(checks.repositoryCount||0),second=String(student.grade)==='2',issues=[];
  const add=(code,label,priority,required=true)=>issues.push({code:code,label:label,priority:priority,required:required});
  const days=Number(g.active_days_7d||0),githubOK=g.check_status==='SUCCESS'&&days>=3,repositoryOK=count>0,readmeOK=readme.readme_status==='README 양호',portfolioRegistered=Boolean(student.notion_url||student.portfolio_url||student.github_pages_url||student.blog_url),notionOK=student.notion_url&&notion.check_status==='SUCCESS'&&notion.activity_status==='최근 업데이트',otherPortfolioOK=checks.publicPortfolio&&checks.publicPortfolio.check_status==='SUCCESS'&&String(checks.publicPortfolio.site_available).toLowerCase()==='true',portfolioOK=Boolean(notionOK||otherPortfolioOK),resumeOK=student.resume_status==='최종 완성',coverOK=['기본본 완성','기업 지원 가능'].includes(student.cover_letter_status);
  if(g.inactive_days!==''&&Number(g.inactive_days)>=14)add('github_inactive','GitHub 14일 이상 미활동',1);
  if(!repositoryOK)add('repository_missing','Repository 미등록',2);
  if(repositoryOK&&readme.readme_status==='README 미작성')add('readme_missing','README 미작성',3);
  else if(repositoryOK&&!readmeOK)add('readme_quality',readme.readme_status||'README 점검 필요',4);
  if(repositoryOK&&readme.readme_exists){if(!readme.role)add('readme_role','README 본인 역할 미작성',5);if(!readme.troubleshooting)add('readme_troubleshooting','README 트러블슈팅 부족',6)}
  if(!githubOK)add('github_days',g.check_status==='SUCCESS'?`최근 7일 GitHub 활동 ${days}일 · 권장 3일`:'GitHub 활동 점검 필요',7);
  if(repositoryOK&&repo.check_status==='SUCCESS'){if(!repo.description_exists)add('description','Repository description 미등록',8);if(!Number(repo.topics_count||0))add('topic','Repository topic 미등록',9);if(!repo.gitignore_exists)add('gitignore','.gitignore 미작성',10);if(!repo.license_exists)add('license','LICENSE 미등록',90,false)}
  if(!portfolioRegistered)add('portfolio_missing','포트폴리오 미등록',11);else if(!portfolioOK)add('portfolio_update',notion.activity_status==='장기 미업데이트'?'포트폴리오 장기 미수정':'포트폴리오 접근·업데이트 확인 필요',12);
  if(second&&!resumeOK)add('resume','이력서 미완성',3);if(second&&!coverOK)add('cover','자기소개서 미완성',4);
  const gates=[githubOK,repositoryOK,readmeOK,portfolioRegistered,portfolioOK].concat(second?[resumeOK,coverOK]:[]),met=gates.filter(Boolean).length,all=gates.every(Boolean),status=all?'준비 우수':met>=Math.ceil(gates.length*.7)?'준비 양호':met>0?'준비 중':'관심 필요';issues.sort((a,b)=>a.priority-b.priority);
  return{status:status,github:{active_days_7d:days,active_days_14d:Number(g.active_days_14d||0),activity_status:g.activity_status||'미점검',inactive_days:g.inactive_days},repository:{count:count,push_status:repo.push_status||'미점검'},readme:{status:readme.readme_status||'미점검'},portfolio:{registered:portfolioRegistered,status:!portfolioRegistered?'미등록':notionOK?'최근 업데이트':portfolioOK?'정상 접근 가능':notion.activity_status||'등록됨'},documents:second?{resume:student.resume_status||'미작성',cover_letter:student.cover_letter_status||'미작성'}:null,issues:issues,priorityIssues:issues.filter(x=>x.required).slice(0,3)}
}
function readinessContext(){return{github:latestMap('GITHUB_CHECK','student_id'),repository:latestMap('REPOSITORY_CHECK','repo_id'),readme:latestMap('README_CHECK','repo_id'),notion:latestMap('NOTION_CHECK','student_id'),portfolio:latestMap('PORTFOLIO_CHECK','student_id'),blog:latestMap('BLOG_CHECK','student_id'),repos:active('REPOSITORIES'),certs:active('CERTIFICATES')}}
function evaluatedStudent(s,c){const sid=String(s.student_id),repos=c.repos.filter(r=>String(r.student_id)===sid).sort((a,b)=>Number(String(b.is_primary).toLowerCase()==='true')-Number(String(a.is_primary).toLowerCase()==='true')||Number(a.display_order||99)-Number(b.display_order||99)),primary=repos[0]||{},github=c.github[sid]||{},repo=c.repository[String(primary.repo_id)]||{},readme=c.readme[String(primary.repo_id)]||{},notion=c.notion[sid]||{},blog=c.blog[sid]||{},portfolio=c.portfolio[sid]||{},evaluation=evaluateStudentReadiness(s,{github:github,repository:repo,readme:readme,notion:notion,blog:blog,publicPortfolio:portfolio,repositoryCount:repos.length});return{student:s,github:github,repository:repo,readme:readme,notion:notion,blog:blog,repositories:repos,evaluation:evaluation,certificateCount:c.certs.filter(x=>String(x.student_id)===sid&&x.status==='취득').length}}
