let READY_DB_CACHE;
function db(){if(READY_DB_CACHE)return READY_DB_CACHE;const sid=props().getProperty('SPREADSHEET_ID');if(!sid)throw publicError('CONFIG_ERROR','Spreadsheet 설정이 필요합니다.');READY_DB_CACHE=SpreadsheetApp.openById(sid);return READY_DB_CACHE}
function initializeSpreadsheet(){const ss=db();Object.keys(READY.SHEETS).forEach(name=>{let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);const headers=READY.SHEETS[name];if(sh.getLastRow()===0)sh.getRange(1,1,1,headers.length).setValues([headers]).setFontWeight('bold').setBackground('#e8eef8');else{const existing=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String),missing=headers.filter(h=>!existing.includes(h));if(missing.length)sh.getRange(1,existing.length+1,1,missing.length).setValues([missing]).setFontWeight('bold').setBackground('#e8eef8')}sh.setFrozenRows(1)});return{spreadsheetId:ss.getId(),sheets:Object.keys(READY.SHEETS)}}
function rows(name){const sh=db().getSheetByName(name);if(!sh||sh.getLastRow()<2)return[];const h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];return sh.getRange(2,1,sh.getLastRow()-1,h.length).getValues().map((v,i)=>Object.assign({_row:i+2},Object.fromEntries(h.map((x,j)=>[x,v[j]]))))}
function sheetHeaders(sh){return sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String)}
function append(name,obj){const sh=db().getSheetByName(name),h=sheetHeaders(sh);sh.appendRow(h.map(k=>obj[k]===undefined?'':obj[k]));return obj}
function upsert(name,key,obj){const all=rows(name),hit=all.find(r=>String(r[key])===String(obj[key])),sh=db().getSheetByName(name),h=sheetHeaders(sh);if(hit){const merged=Object.assign({},hit,obj);sh.getRange(hit._row,1,1,h.length).setValues([h.map(k=>merged[k]===undefined?'':merged[k])]);return merged}return append(name,obj)}
function updateRow(name,row,obj){const sh=db().getSheetByName(name),h=sheetHeaders(sh),merged=Object.assign({},row,obj);sh.getRange(row._row,1,1,h.length).setValues([h.map(k=>merged[k]===undefined?'':merged[k])]);return merged}
function active(name){return rows(name).filter(r=>String(r.active).toLowerCase()!=='false'&&r.active!==0)}
function safeRow(r){const o=Object.assign({},r);delete o._row;delete o.pin_hash;return o}
