function cleanUrl(v){if(!v)return'';if(!/^https?:\/\//i.test(v))throw publicError('INVALID_URL','URL은 http:// 또는 https://로 시작해야 합니다.');return String(v).trim()}
function githubParts(url){const m=String(url||'').match(/^https?:\/\/github\.com\/([^\/]+)(?:\/([^\/#?]+))?/i);return m?{owner:m[1],repo:(m[2]||'').replace(/\.git$/,'')}:null}
function registerStudent(req){if(!/^\d+$/.test(String(req.student_id||''))||!/^[0-9]{6}$/.test(String(req.pin||'')))throw publicError('INVALID_INPUT','학번과 6자리 PIN을 확인해 주세요.');if(!['1','2'].includes(String(req.grade||'')))throw publicError('INVALID_INPUT','학년을 선택해 주세요.');const lock=LockService.getScriptLock();lock.waitLock(10000);try{if(active('STUDENTS').some(s=>String(s.student_id)===String(req.student_id)))throw publicError('DUPLICATE_STUDENT','이미 등록된 학번입니다.');const gp=githubParts(cleanUrl(req.github_url));if(!gp)throw publicError('INVALID_GITHUB_URL','GitHub 프로필 URL을 확인해 주세요.');const t=now(),student={student_id:String(req.student_id),name:String(req.name||'').trim(),grade:String(req.grade),career_target:req.career_target,github_username:gp.owner,github_url:req.github_url,github_pages_url:cleanUrl(req.github_pages_url),github_pages_repo:cleanUrl(req.github_pages_repo),notion_url:cleanUrl(req.notion_url),portfolio_url:cleanUrl(req.portfolio_url),blog_url:cleanUrl(req.blog_url),resume_status:req.resume_status||'미작성',cover_letter_status:req.cover_letter_status||'미작성',pin_hash:hashPin(req.pin),active:true,created_at:t,updated_at:t,last_manual_update_at:t};append('STUDENTS',student);(req.repositories||[]).forEach((url,i)=>addRepository({student_id:student.student_id,role:'STUDENT'},{repo_url:url,is_primary:i===0,display_order:i+1}));history(student.student_id,'등록','student','',student.name,'STUDENT');return{token:newSession('STUDENT',student.student_id),student:safeRow(student)}}finally{lock.releaseLock()}}
function getMyProfile(s){const student=active('STUDENTS').find(x=>String(x.student_id)===String(s.student_id));return{student:safeRow(student),repositories:active('REPOSITORIES').filter(x=>String(x.student_id)===String(s.student_id)).map(safeRow),certificates:active('CERTIFICATES').filter(x=>String(x.student_id)===String(s.student_id)).map(safeRow)}}
function updateMyProfile(s,p){const allowed=['grade','career_target','github_url','github_pages_url','github_pages_repo','notion_url','portfolio_url','blog_url','resume_status','cover_letter_status'],student=active('STUDENTS').find(x=>String(x.student_id)===String(s.student_id));if(!student)throw publicError('NOT_FOUND','학생 정보를 찾을 수 없습니다.');const changes={};allowed.forEach(k=>{let v=p[k]||'';if(k==='grade'&&!['1','2'].includes(String(v)))return;if(k.includes('url')||k==='github_pages_repo')v=cleanUrl(v);if(String(student[k]||'')!==String(v)){history(s.student_id,'프로필',k,student[k],v,'STUDENT');changes[k]=v}});if(changes.github_url){const gp=githubParts(changes.github_url);if(!gp)throw publicError('INVALID_GITHUB_URL','GitHub URL을 확인해 주세요.');changes.github_username=gp.owner}return safeRow(updateRow('STUDENTS',student,Object.assign(changes,{updated_at:now(),last_manual_update_at:now()})))}
function addRepository(s,r){const mine=active('REPOSITORIES').filter(x=>String(x.student_id)===String(s.student_id));if(mine.length>=5)throw publicError('LIMIT_EXCEEDED','Repository는 최대 5개까지 등록할 수 있습니다.');const p=githubParts(cleanUrl(r.repo_url));if(!p||!p.repo)throw publicError('INVALID_REPOSITORY','GitHub Repository URL을 확인해 주세요.');if(mine.some(x=>x.repo_owner.toLowerCase()===p.owner.toLowerCase()&&x.repo_name.toLowerCase()===p.repo.toLowerCase()))throw publicError('DUPLICATE_REPOSITORY','이미 등록된 Repository입니다.');const t=now(),o={repo_id:id('repo'),student_id:s.student_id,repo_owner:p.owner,repo_name:p.repo,repo_url:r.repo_url,is_primary:String(r.is_primary)==='true'||r.is_primary===true,display_order:r.display_order||mine.length+1,active:true,registered_at:t,updated_at:t};append('REPOSITORIES',o);history(s.student_id,'Repository','추가','',o.repo_url,'STUDENT');return safeRow(o)}
function updateRepository(s,req){const r=active('REPOSITORIES').find(x=>x.repo_id===req.repo_id&&String(x.student_id)===String(s.student_id));if(!r)throw publicError('NOT_FOUND','Repository를 찾을 수 없습니다.');return safeRow(updateRow('REPOSITORIES',r,{is_primary:Boolean(req.is_primary),display_order:Number(req.display_order)||r.display_order,updated_at:now()}))}
function removeRepository(s,rid){const r=active('REPOSITORIES').find(x=>x.repo_id===rid&&String(x.student_id)===String(s.student_id));if(!r)throw publicError('NOT_FOUND','Repository를 찾을 수 없습니다.');updateRow('REPOSITORIES',r,{active:false,updated_at:now()});history(s.student_id,'Repository','비활성화',r.repo_url,'','STUDENT');return{removed:true}}
function addCertificate(s,c){const t=now(),o={certificate_id:id('cert'),student_id:s.student_id,certificate_name:String(c.certificate_name||'').trim(),status:c.status||'준비중',acquired_date:c.status==='취득'?c.acquired_date||'':'',active:true,created_at:t,updated_at:t};if(!o.certificate_name)throw publicError('INVALID_INPUT','자격증명을 입력해 주세요.');append('CERTIFICATES',o);history(s.student_id,'자격증','추가','',o.certificate_name+' '+o.status,'STUDENT');return safeRow(o)}
function updateCertificate(s,req){const c=active('CERTIFICATES').find(x=>x.certificate_id===req.certificate_id&&String(x.student_id)===String(s.student_id));if(!c)throw publicError('NOT_FOUND','자격증을 찾을 수 없습니다.');history(s.student_id,'자격증','상태',c.status,req.status,'STUDENT');return safeRow(updateRow('CERTIFICATES',c,{status:req.status,acquired_date:req.acquired_date||'',updated_at:now()}))}
function removeCertificate(s,cid){const c=active('CERTIFICATES').find(x=>x.certificate_id===cid&&String(x.student_id)===String(s.student_id));if(!c)throw publicError('NOT_FOUND','자격증을 찾을 수 없습니다.');updateRow('CERTIFICATES',c,{active:false,updated_at:now()});history(s.student_id,'자격증','비활성화',c.certificate_name,'','STUDENT');return{removed:true}}
function history(sid,category,field,oldV,newV,by){append('CHANGE_HISTORY',{history_id:id('hist'),student_id:sid,changed_at:now(),category:category,field_name:field,old_value:String(oldV||''),new_value:String(newV||''),changed_by:by})}
function getChangeHistory(sid){return rows('CHANGE_HISTORY').filter(x=>String(x.student_id)===String(sid)).sort((a,b)=>String(b.changed_at).localeCompare(String(a.changed_at))).map(safeRow)}
